# Generated by Django 3.0 on 2020-04-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('owner', 'receiver'), name='unique_chat'),
        ),
    ]
