# Generated by Django 3.0 on 2020-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200416_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Was Message Seen'),
        ),
    ]
