// AUTH ACTION
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const RESTORE_USERID = 'RESTORE_USERID';
// CHAT ACTIONS
export const SET_CHATSLIST = 'SET_CHATSLIST';
export const ADD_CHAT = 'ADD_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';
export const SET_CHAT = 'SET_CHAT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RETRY_MESSAGES = 'RETRY_MESSAGES';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const MESSAGES_READ = 'MESSAGES_READ';
export const ADD_WEBSOCKET_CONNECTION = 'ADD_WEBSOCKET_CONNECTION';
export const SET_CHAT_INFO_LOADING_STATUS = 'SET_CHAT_INFO_LOADING_STATUS';

