# Generated by Django 3.0 on 2020-04-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_user', '0002_auto_20200408_1253'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='inv_user',
        ),
    ]
